upload:
  stage: deploy
  image: debian:trixie
  before_script:
    - apt update && apt install -yy curl make build-essential pkg-config
      libpcre2-dev libssl-dev libyaml-dev zlib1g-dev
    - export MISE_INSTALL_PATH="/usr/local/bin/mise"
    - export PATH="/root/.local/share/mise/shims:$PATH"
    - curl https://mise.run | sh
    - mise install
  script:
    - make build-release
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --upload-file bin/bigbrother \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/bigbrother/${CI_COMMIT_TAG}/bigbrother"
