variables:
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}

stages:
  - release
  - deploy

deploy:
  stage: deploy
  image: docker:dind
  script:
    - export IMAGE_TAG=${CI_COMMIT_SHA:0:7}
    - export IMAGE_TAG_ALIASES=${IMAGE_TAG}-x86_64
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - ci/build_and_push
