variables:
  CRYSTAL_VERSION: "0.35.1"

stages:
  - release
  - deploy

release:
  image: crystallang/crystal:${CRYSTAL_VERSION}-build
  stage: release
  artifacts:
    paths:
      - bin
    expire_in: 2 days
  script:
    - make build-release

deploy:
  stage: deploy
  image: docker:dind
  dependencies:
    - release
  script:
    - export IMAGE_TAG=${CI_COMMIT_SHA:0:7}
    - export IMAGE_TAG_ALIASES=${IMAGE_TAG}-x86_64
    - ci/build_and_push

release i386:
  image: crystallang/crystal:${CRYSTAL_VERSION}-i386-build
  stage: release
  artifacts:
    paths:
      - bin
    expire_in: 2 days
  script:
    - make build-release

deploy i386:
  stage: deploy
  image: docker:dind
  dependencies:
    - release i386
  script:
    - export IMAGE_TAG=${CI_COMMIT_SHA:0:7}-i386
    - ci/build_and_push
