stages:
  - release
  - deploy

release:
  image: crystallang/crystal:0.23.0
  stage: release
  artifacts:
    paths:
      - bin
    expire_in: 2 days
  script:
    - make build-release

.build_and_push: &build_and_push
  image: docker:dind
  stage: deploy
  dependencies:
    - release
  script:
    - export IMAGE_TAG=$CI_COMMIT_SHA
    - ci/build_and_push

deploy:
  # Set secure variable IMAGE_NAME
  <<: *build_and_push
